/* eslint-disable */
function History() {
  return (
    <>
      <h1>History</h1>
      <p>In 1994, Canadian games journalist Geoff Keighley had been part of the first televised awards show for video games, Cybermania '94. Keighley, as a teenager, had been brought on to help write material for the celebrity hosts such as William Shatner and Leslie Nielsen. The show was not considered successful, aimed more for comedy than celebration, but he had been prompted from it to develop something akin to the Academy Awards for video games later in his career.</p>

      <p>Keighley had subsequently worked on the Spike Video Game Awards (VGA), which ran from 2003 to 2013. The show was broadcast on Spike TV near the end of each calendar year, and was designed to honor video games released during that year. Keighley served as the producer and often host for these shows. While the network had shown strong support for the award show through 2012, having brought Samuel L. Jackson to host the show, Keighley found Spike less interested in pursuing the 2013 show, partially due to the network seeking less male-oriented programming. Spike opted to rename the awards from VGA to VGX as to reflect that they wanted to focus more on next-generation games that were being ushered in by the onset of the eighth generation of consoles, as well as bringing comedian Joel McHale to co-host alongside Keighley. Additionally, the show was reduced to a one-hour presentation, which was first streamed online before airing on television. The 2013 show was considered to be disappointing and aimed as a more commercial work rather than a celebration of video game achievements. Keighley was disappointed with the change in tone that this show has presented. Spike offered to continue the show in 2014, but would be limited to streaming media rather than broadcast. Keighley opted to drop out from further involvement in the VGX, allowing Spike to retain ownership of the property; in November 2014, Spike TV announced that they had opted to drop the awards show in its entirety.</p>

      <p>Keighley worked with several entities within the industry, including console hardware manufacturers Sony, Microsoft, and Nintendo, and several large publishers, to financially back and craft a new awards show, the Game Awards, with Spike's permission. He invested around US$1 million of his own personal funds to support the new show, and was able to secure space at The AXIS theater in Las Vegas for hosting the live event. Without a broadcaster, Keighley and the other producers agreed to live stream the show on the consoles' networks and on Valve's Steam service to be able to reach a much larger audience than Spike TV previously had.</p>

      <p>Since the 2014 show, Keighley has been able to secure the larger Microsoft Theater in Los Angeles to host the event. He has worked to partner with multiple streaming services around the globe for the show, which has been a move appreciated by several of the Game Awards' partners since the show's inception. Keighley has been approached by broadcast networks offering to air the show, but he had refused these offers, allowing them to keep the freedom of how they present and structure the show. The 2019 show included a simulcast in partnership with Sony Pictures for select Cinemark movie theaters throughout the United States.[10] The Game Awards 2020 was not held in a live theater due to the COVID-19 pandemic and was instead hosted virtually. The 2021 show was held live again at the Microsoft Theater with a reduced audience due to ongoing COVID-19 precautions.</p>


      <p>An illustration of the award statuette, designed by Keighley and Weta Workshop</p>
      
      <p>Keighley considered it important that the Game Awards are aimed to favorably present the interest of gamers and the industry at large, as well as being welcoming to celebrities and others that have shown interest in video games. While the Game Awards are principally an awards show, Keighley knew the importance of having additional content, having seen other experiments of video game awards shows that were only dedicated to awards fail due to lack of audience. Keighley believed that the Game Awards should fall somewhere between the entertainment venues that are used for the Academy Awards and the standard award presentation used for the Game Developers Choice Awards, and wanted a balance of material. Through the Spike VGX and into the Game Awards, Keighley has engaged with games studios to bring reveals of new games alongside the awards. He considers the crowning moment of this approach was being able to secure the first gameplay reveal of The Legend of Zelda: Breath of the Wild at The Game Awards 2014.[13] Keighly encourages game studios to provide any content that might be deemed exciting or that can pique interest, even if these games are at an early stage of development, and then makes the selection of which games and trailers to feature. Keighley subsequently works with those studios about how to best position their trailers to have the most impact; for example, in the 2018 show, he and Nintendo worked on a trailer reveal for the Persona 5 character Joker in Super Smash Bros. Ultimate that appeared to start as a teaser for a new game in the series.</p>

      <p>Since the show's launch, Keighley has solicited input from fans on how to improve the show, typically while at trade shows and conventions in months ahead of the show. For 2020, with the COVID-19 pandemic causing cancellations of many of these events, Keighley invited about one hundred fans to private chats with himself and other top organizers of the program to help solicit their input. The Game Awards were still held in 2020 and 2021, though with a limited invited audience for the latter and limited interactions of hosts, presenters and nominees due to restrictions set by California and Los Angeles in regards to large gatherings in indoor spaces. The 2022 show returned to a full live audience as these government restrictions were since lifted.</p>

      <p>In conjunction with the show, digital storefronts such as Steam, Xbox Games Store, Nintendo eShop, and PlayStation Store offer the nominated games on sale leading up to and a few days after the event. The statuette awarded to the selected games was designed by collaboration between Keighley and Weta Workshop. It is meant to represent "the evolution of the video game medium by way of an angel that ascends through digital building blocks".</p>

      <p>On June 25, 2023, Keighley hosted The Game Awards 10-Year Celebration, a night of video game music at the Hollywood Bowl backed by the Los Angeles Philharmonic.</p>
    </>
  );
}

export default History;
